// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnuclticnlrlpkqhzrpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdudWNsdGljbmxybHBrcWh6cnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTUyMTcsImV4cCI6MjA2Mzc3MTIxN30.AjNA-Ozz6eeGSbxLnH8KeCB7ZvqEfLn-GlxnRWtlqSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);