// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://csgnebdyyuezzdcozhjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZ25lYmR5eXVlenpkY296aGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDQ1NjMsImV4cCI6MjA3MDU4MDU2M30.vVeC49l4zHFTACHJVX8pJ8bcG6tq2A4s1ERUaR7aS-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});